name: 'Testing the Punycode Deprications'

on:
  workflow_dispatch: # Allows manual triggering
permissions:
  issues: write
  pull-requests: write
  actions: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: chiranjib-swain/stale@actions-github-upgrade
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'This issue is stale because it has been open for 200 days with no activity.'
          stale-pr-message: 'This pull request is stale because it has been open for 200 days with no activity.'
          close-issue-reason: 'completed'
          days-before-issue-stale: 200
          days-before-pr-stale: 200
          days-before-close: 2
          remove-stale-when-updated: 'true'
